import dbConnect from 'src/backend/dbConnect';
import Order from 'src/backend/models/ordermodel';
import AdminPageTitle from 'src/components/common/admin/AdminPageTitle';
import Empty from 'src/components/common/admin/Empty';
import CustomPagination from 'src/components/common/shared/CustomPagination';
import AdminAuthLayout from 'src/components/layouts/AdminAuthLayout';
import Head from 'next/head';
import Link from 'next/link';
import { ReactElement, useState } from 'react';
import { HiEye } from 'react-icons/hi';

type OrderType = {
	_id: string;
	status: string;
	qty: number;
	total: number;
	email: string;
	createdAt: Date;
};

const Orders = ({ orders }: { orders: OrderType[] }) => {
	const [page, setPage] = useState(1);
	return (
		<>
			<Head>
				<title>Orders List</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
			</Head>
			<div id="orders">
				<div className="pb-8 flex items-center justify-between">
					<div>
						<AdminPageTitle
							title={'Orders'}
							subtitle={'Admin / Product / Order'}
						/>
					</div>
					<div className="flex  items-center gap-3">
						<input
							type="text"
							placeholder="Search by name..."
							className="input__field"
						/>
						<select className="input__field">
							<option value="">Status</option>
							<option value="">Mens</option>
							<option value="">Women</option>
							<option value="">Fashion</option>
						</select>
						<button className="submit__btn">Search</button>
					</div>
				</div>

				<div className="bg-white p-10 rounded-lg">
					{orders.length > 0 ? (
						<>
							<table className="w-full border-collapse">
								<thead className="bg-[#F0F1FF] border border-[#F0F1FF]">
									<tr>
										<th className="text-left py-3 pl-3">
											<input
												type="checkbox"
												name=""
												id=""
											/>
										</th>
										<th className="text-left py-3">
											Order No.
										</th>
										<th className="text-left py-3">
											Customer
										</th>
										<th className="text-left py-3">
											Created
										</th>
										<th className="text-left py-3">
											Status
										</th>
										<th className="text-left py-3">
											Items
										</th>
										<th className="text-left py-3">
											Total
										</th>
										<th className="text-center py-3 pr-3">
											Action
										</th>
									</tr>
								</thead>
								<tbody>
									{orders.map((item, index) => (
										<tr
											className="border border-[#F0F1FF] mb-2"
											style={{
												marginBottom: '10px',
											}}
											key={index}
										>
											<td className="pl-3 py-3">
												<input
													type="checkbox"
													name=""
													id=""
												/>
											</td>
											<td className="py-3">{item._id}</td>
											<td>{item.email}</td>
											<td className="py-3">
												{new Date(
													item.createdAt,
												).toLocaleString('en-US', {
													timeZone: 'UTC',
													weekday: 'short',
													year: 'numeric',
													month: 'short',
													day: 'numeric',
												})}
											</td>
											<td className="py-3">
												<span className="bg-green-300 text-[#000] text-sm py-1 px-2 rounded-md capitalize">
													{item.status}
												</span>
											</td>
											<td className="py-3">{item.qty}</td>
											<td className="py-3">
												${item.total.toFixed(2)}
											</td>
											<td className="pr-3 py-3">
												<div className="flex items-center gap-2 justify-center">
													<Link
														href={`/admin/orders/${item._id}`}
														className="action__view"
													>
														<HiEye className="text-[#000] text-base" />
													</Link>
												</div>
											</td>
										</tr>
									))}
								</tbody>
							</table>
							<div className="flex items-center justify-end pt-8">
								<CustomPagination
									currentpage={2}
									totalPage={5}
									handler={setPage}
								/>
							</div>
						</>
					) : (
						<Empty text={'No Order Yet'} />
					)}
				</div>
			</div>
		</>
	);
};
Orders.getLayout = function getLayout(page: ReactElement) {
	return <AdminAuthLayout>{page}</AdminAuthLayout>;
};

export async function getServerSideProps(context: any) {
	await dbConnect();
	const data = await Order.find({})
		.select('_id email status createdAt qty total')
		.limit(9);
	return {
		props: { orders: JSON.parse(JSON.stringify(data)) },
	};
}

export default Orders;
