import Head from 'next/head';
import { ReactElement } from 'react';
import DefaultLayout from 'src/components/layouts/DefaultLayout';

const PageNotFound = () => {
	return (
		<>
			<Head>
				<title>404 Page not found</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<meta
					name="viewport"
					content="width=device-width, initial-scale=1"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<div className="error font-mulish">
				<div className="container mx-auto">
					<div className="h-[200px] sm:h-[400px] flex flex-col items-center justify-center gap-4">
						<h3 className="text-4xl font-bold text-center text-[#000]">
							404
						</h3>
						<p className="text-lg font-normal text-center text-[#000]">
							Page Not Found
						</p>
					</div>
				</div>
			</div>
		</>
	);
};

PageNotFound.getLayout = function getLayout(page: ReactElement) {
	return <DefaultLayout>{page}</DefaultLayout>;
};

export default PageNotFound;
