import ProtectedRouted from 'src/components/layouts/ProtectedRoute';
import { Elements } from '@stripe/react-stripe-js';
import { loadStripe } from '@stripe/stripe-js';
import dynamic from 'next/dynamic';
import Head from 'next/head';
import { ReactElement } from 'react';

const CheckoutBody = dynamic(
	() => import('src/components/checkout/CheckoutBody'),
	{
		ssr: false,
	},
);

const stripePromise = loadStripe(`${process.env.STRIPE_PUBLISH_KEY}`);

const Checkout = () => {
	return (
		<>
			<Head>
				<title>Lisk - Checkout</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<meta
					name="viewport"
					content="width=device-width, initial-scale=1"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Elements stripe={stripePromise}>
				<CheckoutBody />
			</Elements>
		</>
	);
};
Checkout.getLayout = function getLayout(page: ReactElement) {
	return <ProtectedRouted>{page}</ProtectedRouted>;
};
export default Checkout;
