import AdBanner from 'src/components/common/shared/AdBanner';
import ProductSlider from 'src/components/common/shared/ProductSlider';
import Spinner from 'src/components/common/shared/Spinner';
import StorePolicy from 'src/components/common/shared/StorePolicy';
import FlashDeal from 'src/components/home/FlashDeal';
import DefaultLayout from 'src/components/layouts/DefaultLayout';
import { useFetchData } from 'src/hooks/useApi';
import Head from 'next/head';
import { ReactElement } from 'react';

const Home = () => {
	const { data: homeProduct, isLoading } = useFetchData(
		'/api/product/homeproduct',
		'home-product',
		1,
	);
	return (
		<>
			<Head>
				<title>Lisk Furniture Store</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<meta
					name="viewport"
					content="width=device-width, initial-scale=1"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>

			{isLoading ? (
				<div className="flex items-center justify-center h-[450px]">
					<Spinner />
				</div>
			) : (
				<>
					{homeProduct.newArrival.length > 0 && (
						<div className="bg-gray-light py-24">
							<h3 className="text-black lg:text-3xl text-2xl font-extrabold text-center font-mulish pb-8">
								New Arrival
							</h3>
							<ProductSlider products={homeProduct.newArrival} />
						</div>
					)}
					<AdBanner />
					{homeProduct.flashDealItems && (
						<FlashDeal
							flashDealItem={homeProduct.flashDealItems.flashDeal}
							countDown={
								homeProduct.flashDealItems.flashDealCountDown
							}
						/>
					)}
					<StorePolicy />
				</>
			)}
		</>
	);
};

Home.getLayout = function getLayout(page: ReactElement) {
	return <DefaultLayout>{page}</DefaultLayout>;
};

export default Home;
