import Head from 'next/head';
import Link from 'next/link';
import { ReactElement } from 'react';
import { FaRegHeart } from 'react-icons/fa';
import { RiDeleteBinLine } from 'react-icons/ri';
import { useDispatch, useSelector } from 'react-redux';
import Picture from 'src/components/common/shared/Picture';
import DefaultLayout from 'src/components/layouts/DefaultLayout';
import { removeFromWishlist } from 'src/redux/slices/wishlistSlice';
import { RootState } from 'src/redux/store';

const WishlistProduct = () => {
	const dispatch = useDispatch();
	const { wishlistItem } = useSelector((state: RootState) => state.wishlist);
	return (
		<>
			<Head>
				<title>Lisk - Wishlist</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<meta
					name="viewport"
					content="width=device-width, initial-scale=1"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<div className="wishlist bg-gray-light py-24">
				{wishlistItem.length > 0 ? (
					<div className="container mx-auto">
						<h3 className="text-black lg:text-3xl text-2xl font-extrabold text-center font-mulish pb-8">
							Your Wishlist
						</h3>
						<div className="grid lg:grid-cols-4 md:grid-cols-3 sm:grid-cols-2 grid-cols-1 lg:gap-8 gap-4">
							{wishlistItem.map((template, index) => (
								<div
									className="bg-white font-mulish p-4 relative"
									key={index}
								>
									{template?.badge && (
										<span className="absolute right-0 bg-orange-dark text-white text-xs inline-block py-1 px-2 top-2/4">
											{template?.badge}
										</span>
									)}
									<span className="text-gray-dark text-xs uppercase">
										{template?.category.title}
									</span>
									<Link href={`/product/${template.slug}`}>
										<h4 className="text-black font-bold text-base mt-2">
											{template?.title.substr(0, 25)}...
										</h4>
									</Link>
									<Link href={`/product/${template.slug}`}>
										<div className="flex justify-center">
											<Picture
												link={`/uploads/${template.thumbnail}`}
												alt={'Product'}
												classList={
													'py-4 h-[230px] w-full'
												}
											/>
										</div>
									</Link>
									<div className="flex items-center justify-between">
										<div className="prices flex items-center">
											<p className="regular-price line-through font-medium text-gray-dark text-sm">
												{template?.regularPrice &&
													`$${template.regularPrice.toFixed(
														2,
													)}}`}
											</p>
											<p className="sale-price text-green-success text-lg font-medium ml-2">
												$
												{template?.salePrice.toFixed(2)}
											</p>
										</div>
										<button
											onClick={() =>
												dispatch(
													removeFromWishlist(
														template,
													),
												)
											}
										>
											<RiDeleteBinLine className="text-gray-dark text-lg" />
										</button>
									</div>
								</div>
							))}
						</div>
					</div>
				) : (
					<div className="flex flex-col items-center">
						<div className="box-shadow h-24 w-24 flex items-center justify-center rounded-full">
							<FaRegHeart className="text-5xl text-black" />
						</div>

						<h2 className="text-black md:text-4xl font-mulish text-xl font-bold my-8">
							Your wishlist is Empty
						</h2>
					</div>
				)}
			</div>
		</>
	);
};
WishlistProduct.getLayout = function getLayout(page: ReactElement) {
	return <DefaultLayout>{page}</DefaultLayout>;
};
export default WishlistProduct;
