import UserAuthLayout from 'src/components/layouts/UserAuthLayout';
import Head from 'next/head';
import { ReactElement, useState } from 'react';
import { HiEye, HiEyeOff } from 'react-icons/hi';

const Security = () => {
	const [showPassword, setShowPassword] = useState({
		currentPassword: false,
		newPassword: false,
		confirmPassword: false,
	});
	type ObjectKey = keyof typeof showPassword;

	return (
		<>
			<Head>
				<title>User password</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<meta
					name="viewport"
					content="width=device-width, initial-scale=1"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<div className="security">
				<h3 className="user-page-title">User Security</h3>
				<form>
					{SecurityChange.map((item, index) => (
						<div className="flex flex-col gap-2 mb-6" key={index}>
							<label
								className="input__label"
								htmlFor="currentPassword"
							>
								{item.label}
							</label>
							<div className="relative w-full">
								<input
									type={
										showPassword[item.name as ObjectKey]
											? 'text'
											: 'password'
									}
									className="input__field block w-full"
								/>
								<div className="absolute inset-y-0 right-4 flex items-center pl-3">
									<button
										type="button"
										onClick={() =>
											setShowPassword({
												...showPassword,
												[item.name]:
													!showPassword[
														item.name as ObjectKey
													],
											})
										}
									>
										{showPassword[
											item.name as ObjectKey
										] ? (
											<HiEyeOff className="text-xl text-[#3a35418a]" />
										) : (
											<HiEye className="text-xl text-[#3a35418a]" />
										)}
									</button>
								</div>
							</div>
						</div>
					))}
					<button className="submit__btn">save changes</button>
				</form>
			</div>
		</>
	);
};

const SecurityChange = [
	{
		name: 'currentPassword',
		label: 'Current Password',
	},
	{
		name: 'newPassword',
		label: 'New Password',
	},
	{
		name: 'confirmPassword',
		label: 'Confirm Password',
	},
];

Security.getLayout = function getLayout(page: ReactElement) {
	return <UserAuthLayout>{page}</UserAuthLayout>;
};
export default Security;
